### ISSUE TITLE
DNS provider --Error: Plugin did not respond

### ISSUE THREAD

**Issue by Spezi2u** [hashicorp/terraform-provider-dns#246]
### Terraform CLI and Provider Versions

$ terraform version
Terraform v1.3.4
on windows_amd64
+ provider registry.terraform.io/e-breuninger/netbox v3.0.10
+ provider registry.terraform.io/hashicorp/dns v3.2.3
+ provider registry.terraform.io/telmate/proxmox v2.9.11

Your version of Terraform is out of date! The latest version
is 1.3.6. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform Configuration

```terraform
#netbox module output.tf
output "ip_vm" {
  description = "The VMs IP Address is: "
  value       = netbox_available_ip_address.pm_vm_ip.ip_address
}

module "dns-add-a-record" {
  source    = "./modules/DNS/add-a-record"
  vm_name   = var.new_name
  ipv4addrs = [module.netbox-new-vm.ip_vm]
}

#module add-a-record main.tf
resource "dns_a_record_set" "a-record" {
  zone      = "${var.domain_tld}."
  name      = var.vm_name
  addresses = var.ipv4addrs
  ttl       = 300
}

resource "dns_ptr_record" "ptr-record" {
  zone = "${var.reverse_zone}."
  name = (format("%s", element(split(".", element(var.ipv4addrs, 0)), 3)))
  ptr  = "${var.vm_name}.${var.domain_tld}."
  ttl  = 300
}
```

### Expected Behavior

Adding a- and ptr record

### Actual Behavior

╷
│ Error: Plugin did not respond
│
│   with module.dns-add-a-record.dns_a_record_set.a-record,
│   on modules\DNS\add-a-record\main.tf line 1, in resource "dns_a_record_set" "a-record":
│    1: resource "dns_a_record_set" "a-record" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with module.dns-add-a-record.dns_ptr_record.ptr-record,
│   on modules\DNS\add-a-record\main.tf line 8, in resource "dns_ptr_record" "ptr-record":
│    8: resource "dns_ptr_record" "ptr-record" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-dns_v3.2.3_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x14ff010]

goroutine 83 [running]:
github.com/miekg/dns.(*Msg).Insert(0xc00019eb40, 0xc00018d128, 0x1, 0x1)
        github.com/miekg/dns@v1.1.47/update.go:75 +0x90
github.com/hashicorp/terraform-provider-dns/internal/provider.resourceDnsARecordSetUpdate(0xc00019c780, 0x1599f40, 0xc0002b9550, 0xc0004067e0, 0xc0001b49c0)
        github.com/hashicorp/terraform-provider-dns/internal/provider/resource_dns_a_record_set.go:114 +0x766
github.com/hashicorp/terraform-provider-dns/internal/provider.resourceDnsARecordSetCreate(0xc00019c780, 0x1599f40, 0xc0002b9550, 0x0, 0xffffffffffffffff)
        github.com/hashicorp/terraform-provider-dns/internal/provider/resource_dns_a_record_set.go:54 +0x67
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0001dcfc0, 0x17dfc00, 0xc0001fe420, 0xc00019c780, 0x1599f40, 0xc0002b9550, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:330 +0x1f6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001dcfc0, 0x17dfc00, 0xc0001fe420, 0xc0001b4270, 0xc00019c600, 0x1599f40, 0xc0002b9550, 0x0, 0x0, 0x0, ...) 
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:472 +0x79d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000004090, 0x17dfb58, 0xc00020e640, 0xc0006be140, 0x16e4d84, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xb0f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002c0000, 0x17dfc00, 0xc000162450, 0xc0002ce000, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x73c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x16a9240, 0xc0002c0000, 0x17dfc00, 0xc000162450, 0xc0004e2300, 0x0, 0x17dfc00, 0xc000162450, 0xc0001840e0, 0xd4)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001cc700, 0x17e95d8, 0xc0000b8340, 0xc000180000, 0xc000202e10, 0x1c5a0c0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001cc700, 0x17e95d8, 0xc0000b8340, 0xc000180000, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0000361e0, 0xc0001cc700, 0x17e95d8, 0xc0000b8340, 0xc000180000)
        google.golang.org/grpc@v1.45.0/server.go:921 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x1fd

Error: The terraform-provider-dns_v3.2.3_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform apply`

if module is tested separately it works as intended

### How much impact is this issue causing?

High

### Additional Information

Tried terraform apply multiple times error is persistent.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Spezi2u** [comment]
Tried to add a CName:


│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to dns_cname_record.this, provider "provider[\"registry.terraform.io/hashicorp/dns\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by Spezi2u** [comment]
Problem resolved. Layer 8 problem used a cidr-ip notation, and that cannot function. Sorry for the bother
